[colors.primary]
background = "#1b2932"
foreground = "#c5cdd3"

[colors.cursor]
text = "#1b2932"
cursor = "#b3d2e6"

[colors.normal]
black = "#182a35"
red = "#c08872"
green = "#72c09f"
yellow = "#c8a984"
blue = "#6196b8"
magenta = "#c28097"
cyan = "#72b7c0"
white = "#c5cdd3"

[colors.bright]
black = "#425866"
red = "#ca8468"
green = "#84c8ab"
yellow = "#d1aa7b"
blue = "#68a4ca"
magenta = "#c88da2"
cyan = "#84c0c8"
white = "#c5d1d3"
